"""Modelo v1.1

Revision ID: 4332a57e304e
Revises: 
Create Date: 2025-09-30 16:47:55.022957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4332a57e304e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('iduser', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('iduser'),
    sa.UniqueConstraint('username')
    )
    op.create_table('project',
    sa.Column('idproject', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=45), nullable=False),
    sa.Column('project_status', sa.String(length=45), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.idcustomer'], ),
    sa.PrimaryKeyConstraint('idproject')
    )
    op.create_table('session',
    sa.Column('idsession', sa.Integer(), nullable=False),
    sa.Column('date_session', sa.String(length=45), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.iduser'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.idcustomer'], ),
    sa.PrimaryKeyConstraint('idsession')
    )
    op.create_table('payment',
    sa.Column('idpayment', sa.Integer(), nullable=False),
    sa.Column('amount_payment', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=45), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.idproject'], ),
    sa.PrimaryKeyConstraint('idpayment')
    )
    op.create_table('invoice',
    sa.Column('idinvoice', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=45), nullable=False),
    sa.Column('type', sa.Enum('factura', 'boleta'), nullable=False),
    sa.Column('payment_idpayment', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_idpayment'], ['payment.idpayment'], ),
    sa.PrimaryKeyConstraint('idinvoice')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invoice')
    op.drop_table('payment')
    op.drop_table('session')
    op.drop_table('project')
    op.drop_table('user')
    # ### end Alembic commands ###
